version: 2.1
jobs: # steps
  build-login:
    working_directory: ~/repo/BackEnd/loginmicroservices

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch

    steps: # a collection of executable commands
      - checkout:
          path: ~/repo

      - restore_cache:
          key: circleci-loginmicroservices-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-loginmicroservices-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/loginmicroservices-0.0.1.jar

  build-book:
    working_directory: ~/repo/BackEnd/bookcatalogmicroservices

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch

    steps: # a collection of executable commands
      - checkout:
          path: ~/repo

      - restore_cache:
          key: circleci-bookcatalogmicroservices-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-bookcatalogmicroservices-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/bookcatalogmicroservices-0.0.1.jar

  build-review:
    working_directory: ~/repo/BackEnd/reviewmicroservices

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch

    steps: # a collection of executable commands
      - checkout:
          path: ~/repo

      - restore_cache:
          key: circleci-reviewmicroservices-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-reviewmicroservices-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/reviewmicroservices-0.0.1.jar

  workflows:
    build:
      jobs:
        - build-login:
            filters:
              branches:
                only: testing
        - build-book:
            filters:
              branches:
                only: testing
        - build-review:
            filters:
              branches:
                only: testing
